### PR TITLE
SETTINGS: add support phone number and email address and use in email templates

### PR DESCRIPTION
**Pull request by pbirl**

### CODE REVIEW

**Comment by cviveiro** [comment]
this one looks good! if you need any help learning how to test it, let me know. you should be able to just go through the flow and then the emails will be printed out into the screen where docker is running. you can verify that it works that way. (you might have already tested this, but figured i'd mention!) and then yeah once tested this is good to be a pr :)))

**Comment by pbirl** [comment]
okay sounds good, for testing we use this command 'docker-compose run pytest' right

**Comment by cviveiro** [comment]
that'll run the unit tests. you can do that definitely, but that won't test what you need to test for this.

you'll want to use the website to do this. run your docker containers, navigate to localhost:3001 on firefox on your workspace, and you should see the website. then, click on the forgot password button and go through that process. after the website says that an email was sent, check the output in the terminal that has the docker container running. it should have printed out the email text. you can check the text there and make sure that the correct phone number and email are shown and no errors occur.

when you make the pr into the main repo, please include info on how you test it and what the test results were. so like for this, mention going through the flow and then copy paste in the output from the docker container around the part of the email that was changed.

**Comment by pbirl** [comment]
Okay perfect thanks for the information. yes i will include steps and screen shots too

**Comment by pbirl** [comment]
I imported support email address and support phone number variables from settings.py to the backend>shared>email.py and tested this change by navigating to localhost:3001. when clicked forgot password after login to the website, the docker container displays the support phone number and email address as output in the terminal.
Support phone number and email address

**Comment by cviveiro** [comment]
awesome! then this is ready to be a real PR into the mlp portunus repo

**Comment by pbirl** [comment]
Yeah thanks for reviewing

**Pull request closed without merging**
